services:
  postgres:
    image: postgres:17
    container_name: care-facility-dx-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: care_dx
      POSTGRES_PASSWORD: care_dx_password
      POSTGRES_DB: care_facility_dx

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
